### PR TITLE
Defining project "`Technology stack`"

### PR DESCRIPTION
**Pull request by xeho91**
**This Pull Request is to open a discussion where we will select the entire technology stack for the project.**

---

### Root

- [x] Define the _root_ technology stack
- [x] Document it in the [README.md] file

### Back-End

- [x] Define the technology stack for the server-side _(Back-End)_
- [x] Document the choices in the [README.md] file - under the "Back-End technology stack" sub-section

### Front-End

- [x] Define the technology stack for the client-side _(Front-End)_
- [x] Document the choices in the [README.md] file - under the "Front-End technology stack" sub-section

[README.md]: ./README.md

### CODE REVIEW

**Comment by xeho91** [comment]
## Front-End Technology UI library & framework options

| UI library | Framework |
| ------------ | --------------- |
| [React]    | [Next.js]      |
| [Vue]       | [Nuxt.js]      |
| [Svelte]   | [SvelteKit]   |

[React]: https://reactjs.org/
[Next.js]: https://nextjs.org/
[Vue]: https://v3.vuejs.org/
[Nuxt.js]: https://nuxtjs.org/
[Svelte]: https://svelte.dev/
[SvelteKit]: https://kit.svelte.dev/

@mariushilleke I'll leave the decision to you; I am flexible about which one you'll choose. I don't want to influence your decision.

**Comment by lax0248917** [comment]
@xeho91 @mariushilleke Guys I jacked this up. Out of habit I added -ALL changes and it brought in all the modules. Gah!!! Such an idiot! So...its time for a lesson with Git. How do I remove the last commit that was pushed and remove it from our history? I copied all the changes I made to readme.md so I can add them back after we fix this error. My apologies. @xeho91 Didn't take long for me to learn the hardway what we discussed about GACP yesterday lol.

**Comment by xeho91** [comment]
> @xeho91 @mariushilleke Guys I jacked this up. Out of habit I added -ALL changes and it brought in all the modules. Gah!!! Such an idiot! So...its time for a lesson with Git. How do I remove the last commit that was pushed and remove it from our history? I copied all the changes I made to readme.md so I can add them back after we fix this error. My apologies. @xeho91 Didn't take long for me to learn the hardway what we discussed about GACP yesterday lol.

Don't worry. It's a PR and a draft. Mistakes are EXPECTED and ALLOWED to happen 😃

First, backup somewhere the content of the commit message.

Since it's the latest commit, you can do for example :
```sh
git reset --soft HEAD~1
```

And remove unexpected files from the staging area. 🙂

OR, you can use https://github.com/jesseduffield/lazygit

And remove these unexpected files from the commit.

In the end, you need to push it with **force**!!!!!!111one
```sh
git push --force
```

**Review by lax0248917 — COMMENTED** [review]
Definitely looks better as a separate table!

**Comment by xeho91** [comment]
This Pull Request needs #42 to be completed first.

**Comment by xeho91** [comment]
@lax0248917 Could I ask you to proofread the Front-End Technology Stack quickly? Also, if there are any typos, please create a commit that fixes them and ready this Pull Request.

**Review by lax0248917 — APPROVED** [review]
LGTM!!! Crushing it today :)

**Pull request merged**
