### PR TITLE
Choosing a project `LICENSE`

### PR DESCRIPTION
**Pull request by xeho91**
**This Pull Request intention is to start the discussion on deciding which project license we should be using.**

---

## TODO

- [x] Create a new file - [LICENSE.md] with the project license
- [x] Add authors/contributors to the license
- [x] Mention _(document)_ the project license in the [README.md] file
- [x] Add a shield _(badge)_ which displays a project license to [README.md] file

[README.md]: ./README.md
[LICENSE.md]: ./LICENSE.md

### CODE REVIEW

**Comment by xeho91** [comment]
**My thoughts**:
Based on my research and using this website: https://choosealicense.com/
I believe the [MIT License](https://choosealicense.com/licenses/mit/) suits our needs the best.

**Review by lax0248917 — APPROVED** [review]
I agree that this license works for us. Its the most common one I see in open source.

**Comment by xeho91** [comment]
This Pull Request needs #42 to be completed first.

**Review by lax0248917 — APPROVED** [review]
LGTM!!!

**Pull request merged**
